apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend
spec:
  replicas: 2
  selector:
    matchLabels:
      app: frontend
  template:
    metadata:
      labels:
        app: frontend
    spec:
      containers:
      - name: frontend
        image: 036160411895.dkr.ecr.ap-southeast-1.amazonaws.com/gaming-microservices/frontend:port-fix-amd64-20250803-235857
        imagePullPolicy: Always
        ports:
        - containerPort: 8080
        env:
        - name: REACT_APP_GAMING_SERVICE_URL
          valueFrom:
            configMapKeyRef:
              name: app-config
              key: GAMING_SERVICE_URL
        - name: REACT_APP_ORDER_SERVICE_URL
          valueFrom:
            configMapKeyRef:
              name: app-config
              key: ORDER_SERVICE_URL
        - name: REACT_APP_ANALYTICS_SERVICE_URL
          valueFrom:
            configMapKeyRef:
              name: app-config
              key: ANALYTICS_SERVICE_URL
        resources:
          requests:
            memory: "256Mi"
            cpu: "100m"
          limits:
            memory: "512Mi"
            cpu: "500m"
---
apiVersion: v1
kind: Service
metadata:
  name: frontend-service
spec:
  selector:
    app: frontend
  ports:
  - port: 80
    targetPort: 8080
  type: ClusterIP
